export const imageRootEnv: any = {
  DEV: process.env.NEXT_PUBLIC_METAHOST_DEV_IMAGEROOTURL,
  UAT: process.env.NEXT_PUBLIC_METAHOST_UAT_IMAGEROOTURL,
  PROD: process.env.NEXT_PUBLIC_METAHOST_PROD_IMAGEROOTURL,
  CLOUDNEW: process.env.NEXT_PUBLIC_METAHOST_CLOUDNEW_IMAGEROOTURL,
  COZY: process.env.NEXT_PUBLIC_METAHOST_COZY_IMAGEROOTURL,
  RIVERDEV: process.env.NEXT_PUBLIC_METAHOST_RIVERDEV_IMAGEROOTURL,
};

export const googleAnalyticsEnv: any = {
  MOTO: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_GAID_MOTO,
  COZY: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_GAID_COZY,
};
